### ISSUE TITLE
Email test button

### ISSUE THREAD

**Issue by AFJreus** [borisbergman/EscMonitoring#103]

**Comment by RamonZwaga** [comment]
functie van de knop is ok, maar dan moet wel blijkbaar het vinkje 'disable auto mail' uitstaan; waarom? je krijgt dan een melding:

'Not all necessary field were filled in, e-mail sending is disabled or timer is not resetted, email not send'

Aangeven welke velden dan nodig zijn!
Test mail button moet de status van vinkje auto mail overrulen
Timer, welke dan?

**Comment by borisbergman** [comment]
timer: die om te voorkomen dat de boel gespamt wordt. zal timer en vinkje overrullen
