### ISSUE TITLE
Popup changes

### ISSUE THREAD

**Issue by borisbergman** [borisbergman/EscMonitoring#107]
Background: Yellow.

Text=> 

Line 1: Enterro VA system 
Line 2: Detected errors/errors acknowledged/errors resetted
Line 3: Click for details

**Comment by RamonZwaga** [comment]
check in edam
typo's
wrong sentences/error reported
error on tab does not highlight

**Comment by borisbergman** [comment]
even specificeren hoe dat ding er uit moet zien.

**Comment by RamonZwaga** [comment]
![image](https://cloud.githubusercontent.com/assets/8523943/11718326/adecb614-9f55-11e5-8706-a66dba54009d.png)

de tekst eronder (met de dubbel puntjes!) zo implementeren

Overigens:
![image](https://cloud.githubusercontent.com/assets/8523943/11718344/c78f1c7e-9f55-11e5-9b2c-b14062176e2f.png)

FaultReseted moet zijn 'Fault Reset' (reseted is geen engels)
