### ISSUE TITLE
error message seems not correct according generated error on ESC

### ISSUE THREAD

**Issue by RamonZwaga** [borisbergman/EscMonitoring#113]
we used ext error contact and when activated we get a line impedance dev at 1kHz line B; should be ext error

When we remove this contact connection we get: ampdefect, amp has an error; but should have been 'connection to ext contact error' 

dan op S4, amplifier losgetrokken, melding is loudspeaker line short circuit; master geeft niet 'slave has errors, maar Loudspeaker line 4 short circuit'

Alsof of de error lijst niet meer klopt.....
Niet alle iconen/lijnen in de moni knipperen juist ....

**Comment by borisbergman** [comment]
Heb je de array van de error waarbij dit fout gaat?

**Comment by borisbergman** [comment]
oeps, fout gemaakt. Hersteld.
