### ISSUE TITLE
Monitoring shutdown and re-start

### ISSUE THREAD

**Issue by RamonZwaga** [borisbergman/EscMonitoring#115]
waarom is mijn achtergrond groen geworden als ik monitoring sluit en dan weer start?
![image](https://cloud.githubusercontent.com/assets/8523943/11718945/b49dbc94-9f58-11e5-9ac8-ab780b7fb748.png)

ook in communicatie window:
![image](https://cloud.githubusercontent.com/assets/8523943/11718952/c5e329ee-9f58-11e5-84a2-36488d3192a3.png)

is nu groen en niet blauw...

**Comment by borisbergman** [comment]
usb: groen, netwerk: blauw
