### ISSUE TITLE
Duplicate loudspeakers in overview (request)

### ISSUE THREAD

**Issue by RamonZwaga** [borisbergman/EscMonitoring#122]
![image](https://user-images.githubusercontent.com/8523943/33311531-56d69ece-d425-11e7-9128-7c6d240b1466.png)

**Comment by RamonZwaga** [comment]
Hi Boris, imagine a hotel project where they have multiple rooms. If we add a speakers from line 1A to this area, we only have one to display. Would it be possible to create a 'loudspeaker duplicate", so when right clicking on the speaker symbol one can create multiple copies of this speaker (with same ID), so we can put a speaker in every room (in this example). Sounds like 15 minutes of work :)

**Comment by borisbergman** [comment]
This reminds me of so many features implemented and so little features eventually delivered. Please stick to testing and talk about new stuff when everything is up and running out of the box. Also, your request is taking way longer than 15 minutes. I'll close it for now, can be reopened in future when above statements are met.
