### ISSUE TITLE
PasswordBox: Show bullets

### ISSUE THREAD

**Issue by borisbergman** [borisbergman/EscMonitoring#96]
When email is send through ssl, a password is entered and saved in the design file. It should be made clear when a password has already been entered.

**Comment by AFJreus** [comment]
Want to have bullets. same amount as the chr count.

**Comment by RamonZwaga** [comment]
1. bij invoer 1ex pw, aantal karakters tellen en opslaan.
2. bij het opnieuw openen van dit veld net zoveel bullets laten zien als char.count.
3. bij aanklikken veld eerst char.count op 0 zetten, dan veld leegmaken zodat pw ingevoerd kan worden

**Comment by RamonZwaga** [comment]
werkt bijna goed, alleen zien we nu '-' streepjes (ipv bulltes) die aangeven dat er al een PW is,

**Comment by borisbergman** [comment]
done
