### ISSUE TITLE
Slave error behaviour incorrect

### ISSUE THREAD

**Issue by borisbergman** [borisbergman/EscMonitoring#98]
When a slave error occurs the master starts blinking but the slave does not.

**Comment by borisbergman** [comment]
Please provide me an error code, I cant reproduce this issue.

**Comment by borisbergman** [comment]
Gewoon wat er staat:

Error komt binnen op slave en wordt door gemeld aan master.

In monitoring software gaat de Master VACIE wel knipperen, maar de Slave VACIE niet

**Comment by borisbergman** [comment]
The master should send [0x01, 0x81, 0x0A, 0x1F, 0x01, 0x05, 0x81, 0x01, 0x01, 0x34] when an error occurs, and the slave does blink on the master tab in this case. 

Please provide me with an error code which didn't give the expected result.

**Comment by AFJreus** [comment]
When an error occurs on a slave unit, both master and slave should be blinking in the overview.

**Comment by RamonZwaga** [comment]
effe testen want voor ons gevoel gaat dan alleen de master knipperen.
Als er dus een slave error is, dan ontvang je van die slave z'n error, naast dat de master 'slave has errors' krijgt. Beide moeten dan in het overview gaan knipperen

**Comment by RamonZwaga** [comment]
zie vorig comment, deze is toch niet zo moeilijk om op te lossen...
Als op Slave 1 een fout ontstaat, dan moet op de Slave 1 tab dit zichtbaar worden, maar...
De master krijgt ook door dat Slave 1 een fout heeft, dus ook de 'master' in het master tab moet gaan knipperen. 
Inhet foutoverzicht onderaan geeft je ook 2 fouten weer (b.v. Slave 1 amplifier error en daarnaast: Master: Slave 1 has errors)
